projectName: nodejs-configvention
projectUrl: http://joelpurra.github.com/nodejs-configvention
projectGithub: https://github.com/joelpurra/nodejs-configvention

googleAnalyticsAccountId: UA-29171100-1